language: ruby
rvm:
- 2.2.3

addons:
  code_climate:
    repo_token:
      secure: uxfQTqKAH/S5LtrPOV8/qb6dPNYwNGkHDjRjjETL0X0jIV9KYofHvJO5cgTwbz1IZGP6fAb8NY0Iek13Q7K5ADpvQqbQicqxjgj2R7WpJggLy7A7Bl66AopRXh+gm8BCrkMyOiAPdZ+sKnTv/fkzf+6EUuVggtuZ+CpG1J26W6ttfhYj6pFqrY1572oBaGc3rKqfRNS01AFLwKzXrImtbetyXwOBEQ+i0tctRNXHkKFjFw4AoK9I3S7TJIh8Ej9QxZXKlk+hHLra7iGktrYWk1CDA41QDdM5EQOhYEP5Zi4zNyw/clJhB7EqKr/CbKMn4wosUfdkUTIKp6aCmqCr2439Hb8b4pr+Mbhv6hHwGwW05jgG/Knqbzs1ymhdyVuE0Zus616lytDn/KZ+KzsunCNiKxj8q8fMw4ksyY/euc2lgYpZq29JlGc2FfF6cgbLTn+ywomAtV7KhwZHssllj+DirvkMCkLN98+nW1YLBYh7wXjKShpo4jzsWAL4n+w08MzL8m7IervEZoWero2MPsL3+0ORCXiVwXJVnh1EVzBv/NldYx18AOILm6NI9Q4GoJ1fKvD8h1spKCuXphf/I/9yDdnzcU+jUX3va2Hwmzg6827xEJQzNVBwyZmiLzESJZb/sspghs6qYASgedzYeA0YLxu2oBp/jG86jVCdKgk=
